brew update

brew upgrade

brew tap homebrew/dupes
brew tap jimbojsb/launchrocket
brew tap Goles/battery
brew tap ravenac95/sudolikeaboss
brew tap phinze/homebrew-cask

brew install brew-cask

brew cask install xquartz

brew install ansible
brew install ansifilter
brew install apple-gcc42
brew install archey
brew install autoconf
brew install battery
brew install cmake
brew install coreutils
brew install cowsay
brew install ctags
brew install curl
brew install direnv
brew install docker
brew install fasd
brew install ffind
brew install fontconfig
brew install fontforge
brew install gcc
brew install git
brew install git-cal
brew install git-flow
brew install gnutls
brew install grc
brew install grep
brew install hr
brew install htop-osx
brew install hub
brew install ifstat
brew install imagemagick
brew install legit
brew install lua
brew install luarocks
brew install luajit
brew install mackup
brew install macvim --override-system-vim --with-lua --with-luajit --custom-icons
brew install node
brew install openssl
brew install phantomjs
brew install postgresql
brew install rainbarf
brew install rbenv
brew install rbenv-binstubs
brew install rbenv-gem-rehash
brew install rbenv-use
brew install rbenv-whatis
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install rsense
brew install ruby-build
brew install sloccount
brew install source-highlight
brew install sqlite
brew install ssh-copy-id
brew install sudolikeaboss
brew install terminal-notifier
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tmux-mem-cpu-load
brew install trash
brew install tree
brew install webkit2png
brew install zsh

brew tap homebrew/versions

brew cleanup
