tap "cjbassi/gotop"
tap "goles/battery"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "instantclienttap/instantclient"

brew "openssl"
brew "readline"
brew 'mas'

brew "aircrack-ng"
brew "automake"
brew "bash"
brew "bat"
brew "bison"
brew "gettext"
brew "gdbm"
brew "libffi"
brew "python"
brew "ccat"
brew "choose-gui"
brew "chruby"
brew "clipper"
brew "cmake"
brew "cmatrix"
brew "coreutils"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "dockutil"
brew "duti"
brew "exa"
brew "fasd"
brew "fd"
brew "sdl2"
brew "ffmpeg"
brew "ghi"
brew "ghostscript"
brew "git-flow"
brew "git-hooks"
brew "go"
brew "hashcat"
brew "hidapi"
brew "lua"
brew "highlight"
brew "hr"
brew "htop"
brew "hub"
brew "ical-buddy"
brew "ifstat"
brew "libtool"
brew "imagemagick"
brew "john"
brew "jq"
brew "libressl"
brew "libsodium"
brew "libtermkey"
brew "libusb"
brew "libyaml"
brew "lnav"
brew "luajit"
brew "m-cli"
brew "protobuf"
brew "mosh", args: ["HEAD"]
brew "ncdu"
brew "ninja"
brew "noti"
brew "pandoc"
brew "pdfcrack"
brew "pkg-config"
brew "portaudio"
brew "postgresql"
brew "qt"
brew "ripgrep"
brew "ruby-install"
brew "rust"
brew "sassc"
brew "ssh-copy-id"
brew "streamlink"
brew "telnet"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "topgrade"
brew "trash-cli"
brew "tree"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "cjbassi/gotop/gotop"
brew "goles/battery/battery"
brew "heroku/brew/heroku"

cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "bartender"
cask "bettertouchtool"
cask "blue-jeans"
cask "calibre"
cask "coconutbattery"
cask "colorpicker-developer"
cask "cyberduck"
cask "daisydisk"
cask "discord"
cask "docker"
# cask "fake"
cask "fantastical"
cask "firefox-developer-edition"
# cask "fluid"
cask "font-3270-nerd-font-mono"
cask "font-anonymouspro-nerd-font-mono"
cask "font-arimo-nerd-font-mono"
cask "font-aurulentsansmono-nerd-font-mono"
cask "font-bitstreamverasansmono-nerd-font-mono"
cask "font-codenewroman-nerd-font-mono"
cask "font-cousine-nerd-font-mono"
cask "font-dejavusansmono-nerd-font-mono"
cask "font-droidsansmono-nerd-font-mono"
cask "font-fantasquesansmono-nerd-font-mono"
cask "font-firacode-nerd-font-mono"
cask "font-firamono-nerd-font-mono"
cask "font-go-mono-nerd-font-mono"
cask "font-gohu-nerd-font-mono"
cask "font-hack-nerd-font"
cask "font-hack-nerd-font-mono"
cask "font-hasklig-nerd-font-mono"
cask "font-heavydata-nerd-font-mono"
cask "font-hermit-nerd-font-mono"
cask "font-inconsolata-nerd-font-mono"
cask "font-inconsolatago-nerd-font-mono"
cask "font-inconsolatalgc-nerd-font-mono"
cask "font-iosevka"
cask "font-iosevka-nerd-font-mono"
cask "font-liberationmono-nerd-font-mono"
cask "font-meslo-nerd-font-mono"
cask "font-monoid-nerd-font"
cask "font-monoid-nerd-font-mono"
cask "font-mononoki-nerd-font"
cask "font-mononoki-nerd-font-mono"
cask "font-mplus-nerd-font-mono"
cask "font-spacemono-nerd-font-mono"
cask "font-terminus-nerd-font-mono"
cask "font-tinos-nerd-font-mono"
cask "font-ubuntu-nerd-font-mono"
cask "font-ubuntumono-nerd-font-mono"
cask "gpg-suite"
cask "hammerspoon"
cask "iina"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keyboard-cleaner"
cask "latest"
cask "lingon-x"
cask "linkliar"
cask "macdown"
cask "macvim"
cask "microsoft-office"
cask "muzzle"
cask "name-mangler"
cask "opera"
cask "pacifist"
cask "paw"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "selfcontrol"
cask "skype"
cask "skype-for-business"
cask "slack"
cask "sloth"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "superduper"
cask "suspicious-package"
cask "tableplus"
cask "the-unarchiver"
cask "vlc"
cask "webpquicklook"

mas "com.acqualia.soulver", id: 413965349
mas "com.amarcus.PiPer", id: 1421915518
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.atlassian.trello", id: 1278508951
mas "com.blackmagic-design.DiskSpeedTest", id: 425264550
# mas "com.grandsoft.MDB-Explorer", id: 506622388
mas "com.helloresolven.GIF-Brewery-3", id: 1081413713
mas "com.houdah.MagicKeyboard", id: 472717129
mas "com.if.Amphetamine", id: 937984704
mas "com.iflicksapp.iFlicks2", id: 731062389
mas "com.pixelmatorteam.pixelmator.x", id: 1289583905
mas "com.reederapp.macOS", id: 1449412482
mas "com.robinlu.mac.Tooth-Fairy", id: 1191449274
mas "com.tapbots.Tweetbot3Mac", id: 1384080005
mas "com.underpassapp.StopTheMadness", id: 1376402589
mas "net.evanm.SmileAllDay", id: 1180442868
mas "org.darkreader.DarkReaderSafari", id: 1438243180
