" set guifont=Fixedsys\ Excelsior:h22
" set guifont=M+\ 1mn\ medium:h22
" set guifont=Operator\ Mono\ Medium:h22
set guifont=Hasklig:h20

set guioptions-=T
set guioptions-=L
set guioptions-=l
set guioptions-=R
set guioptions-=r
set guioptions-=b

set wrap linebreak

if has('title') && (has('gui_running') || &title)
    set titlestring=
    set titlestring+=%f " file name
    set titlestring+=%h%m%r%w " flags
    set titlestring+=\ -\ %{substitute(getcwd(),\ $HOME,\ '~',\ '')}  " working directory
endif

set background=dark

" MacVim GUI only options
if has('gui_macvim')
    " transparency
    set transp=1

  " let g:jellybeans_use_term_italics = 1
  " colorscheme tender

    " full width full screen
    set fuopt+=maxhorz
endif
