# Example Vale config file (`.vale.ini` or `_vale.ini`)

# Core settings
# StylesPath = code/work/packages
StylesPath = code/work/packages/pkg

# The minimum alert level to display (suggestion, warning, or error).
#
# CI builds will only fail on error-level alerts.
MinAlertLevel = suggestion

# The "formats" section allows you to associate an "unknown" format
# with one of Vale's supported formats.
[formats]
mdx = md
gitcommit = txt

# Global settings (applied to every syntax)
[*]
# List of styles to load
BasedOnStyles = write-good, proselint, Readability
#, alex
# Joblint,
