" vim:fdm=marker
" ~/.vimrc
" thanks to the brilliant @tpope, @skwp, @nelstrom, @bling,
" @r00k, @spf13, @AndrewRadev, @junegunn, @wincent, and @sjl for unknowingly
" allowing me to borrow from their dotfiles.

call plug#begin()

" standard {{{ "
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
" }}} standard "

" almost standard {{{ "
Plug 'junegunn/fzf',       { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-oblique'
Plug 'mhinz/vim-sayonara', { 'on': 'Sayonara' }
Plug 'takac/vim-commandcaps'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-ragtag'
Plug 'EinfachToll/DidYouMean'
" }}} almost standard "

" looks {{{ "
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'junegunn/vim-peekaboo'
Plug 'lilydjwg/colorizer', { 'for': ['css', 'sass', 'scss', 'less', 'html', 'javascript'] }
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
" }}} looks "

" colors {{{ "
" Plug 'w0ng/vim-hybrid'
" Plug 'Sclarki/neonwave.vim'
" Plug 'morhetz/gruvbox'
" Plug 'nanotech/jellybeans.vim'
Plug 'whatyouhide/vim-gotham'
" Plug 'freeo/vim-kalisi'
" Plug 'rakr/vim-one'
" Plug 'tyrannicaltoucan/vim-deep-space'
" Plug 'kabbamine/yowish.vim'
" }}} colors "

" ruby {{{ "
Plug 'janko-m/vim-test'
Plug 'ngmy/vim-rubocop',  { 'for': 'ruby' }
Plug 'tpope/vim-bundler', { 'for': ['ruby', 'eruby', 'haml', 'slim'] }
Plug 'tpope/vim-rails',   { 'for': ['ruby', 'eruby', 'haml', 'slim', 'yaml'] }
Plug 'tpope/vim-rake',    { 'for': 'ruby' }
" }}} ruby "

" syntax {{{ "
Plug 'sheerun/vim-polyglot'
Plug 'davejlong/cf-utils.vim',   { 'for': ['coldfusion', 'cfml'] }
Plug 'sunaku/vim-ruby-minitest', { 'for': 'ruby' }
Plug 'chrisbra/csv.vim',         { 'for': 'csv' }
" }}} syntax "

" dependencies {{{ "
Plug 'xolox/vim-misc'
Plug 'junegunn/vim-pseudocl'
" }}} dependencies "

" misc {{{ "
Plug 'Konfekt/FastFold'
" Plug 'ntpeters/vim-better-whitespace'
" Plug 'cohama/lexima.vim'
" Plug 'christoomey/vim-tmux-navigator'
Plug 'AndrewRadev/sideways.vim'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'AndrewRadev/switch.vim'
Plug 'chip/vim-fat-finger'
Plug 'christoomey/vim-sort-motion'
Plug 'christoomey/vim-system-copy'
Plug 'duggiefresh/vim-easydir'
Plug 'dyng/ctrlsf.vim',         { 'on': ['CtrlSF', 'CtrlSFToggle', '<Plug>CtrlSFPrompt' ] }
Plug 'foosoft/vim-argwrap',     { 'on': 'ArgWrap' }
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }
Plug 'scrooloose/nerdtree'
Plug 'thirtythreeforty/lessspace.vim'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-rsi'
Plug 'vim-scripts/BufOnly.vim', { 'on': 'Bonly' }
Plug 'wincent/terminus'
" }}} misc "

" mac/nvim {{{ "
if has('nvim')
  set termguicolors
  Plug 'bfredl/nvim-miniyank'
  Plug 'benekastah/neomake',    { 'on': 'Neomake' }
  source ~/.vim/scripts/completions.vim
else
  Plug 'jszakmeister/vim-togglecursor'
  Plug 'tpope/vim-sensible'
endif
" }}} mac/nvim "

" custom vim objects {{{ "
Plug 'Julian/vim-textobj-brace'
Plug 'beloglazov/vim-textobj-quotes'
Plug 'coderifous/textobj-word-column.vim'
Plug 'glts/vim-textobj-indblock'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-fold'
Plug 'kana/vim-textobj-indent'
Plug 'kana/vim-textobj-user'
Plug 'tek/vim-textobj-ruby'
Plug 'kana/vim-textobj-line'
" }}} custom vim objects "

call plug#end()

source ~/.vim/scripts/autocommands.vim
source ~/.vim/scripts/mappings.vim
source ~/.vim/scripts/plugin_settings.vim

" settings {{{ "
  set virtualedit=onemore   " allow selection past last character
  set expandtab
  set foldlevelstart=99
  set formatprg="par 79"    " respect the 80 character lines
  set gdefault              " assume the /g flag on :s substitutions
  set hidden                " make unsaved buffers hidden
  set ignorecase
  set list
  set listchars=nbsp:⦸      " CIRCLED REVERSE SOLIDUS (U+29B8, UTF-8: E2 A6 B8)
  set listchars+=tab:├─     " WHITE RIGHT-POINTING TRIANGLE (U+25B7, UTF-8: E2 96 B7)
                            " + BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL (U+2505, UTF-8: E2 94 85)
  set listchars+=extends:»  " RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK (U+00BB, UTF-8: C2 BB)
  set listchars+=precedes:« " LEFT-POINTING DOUBLE ANGLE QUOTATION MARK (U+00AB, UTF-8: C2 AB)
  set listchars+=trail:•    " BULLET (U+2022, UTF-8: E2 80 A2)
  if has('linebreak')
    let &showbreak='⤷ '     " ARROW POINTING DOWNWARDS THEN CURVING RIGHTWARDS (U+2937, UTF-8: E2 A4 B7)
  endif
  set nojoinspaces          " don't autoinsert two spaces after '.', '?', '!' for join command
  set noshowmatch           " don't jump between matching brackets
  set noswapfile
  set nowrap
  set shiftround            " indenting to nearest tabstop
  set smartcase             " smartcase for searching
  set splitbelow            " default split behavior
  set synmaxcol=180
  set ttimeoutlen=50        " vim-sensible's is kinda slow
  syntax sync minlines=256  " start highlighting from 256 lines backwards

  set ts=2 sts=2 sw=2
" }}} settings "

" wildignore {{{ "
  set wildignore+=.DS_Store
  set wildignore+=*.jpg,*.jpeg,*.gif,*.png,*.psd,*.min.js,*.sock
  set wildignore+=*/.git/*,*/log/*,*/tmp/*,.keep
  set wildmode=list:longest
" }}} wildignore "

" coloring {{{ "
  if has('nvim')
    set highlight+=@:ColorColumn          " ~/@ at end of window, 'showbreak'
    set highlight+=N:DiffText             " make current line number stand out a little
    set highlight+=c:LineNr               " blend vertical separators with line numbers
  endif
  set background=dark
  colorscheme gotham256
" }}} coloring "

if has('termguicolors')
  " Don't need this in xterm-256color, but do need it inside tmux.
  " (See `:h xterm-true-color`.)
  if &term =~# 'tmux-256color'
    let &t_8f="\e[38;2;%ld;%ld;%ldm"
    let &t_8b="\e[48;2;%ld;%ld;%ldm"
  endif
endif

" Persistent Undo {{{
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  if has("persistent_undo")
    set undodir=~/.vim/backups
    set undofile
  endif
" }}}
