# vim: set ft=zsh:

typeset -U PATH path

source $HOME/.zsh/misc/utility.zsh

# https://github.com/golang/go/issues/68248#issuecomment-2197894974
export GOEXPERIMENT=rangefunc

export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}"
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"

export DOTFILES="$HOME/code/dotfiles"
export GITLAB_MAIN_BRANCH="master" # this will eventually be "main"
export CLI_HOME="$HOME/code/work/cli"
export GDK_ROOT="$HOME/code/work/gdk"
export GDK_DEV_HOME="$HOME/code/work/devkit"
export WORKTREE_PATH="$GDK_ROOT/gitlab-workspaces"
export GITLAB_HOME="$GDK_ROOT/gitlab"

export OPENCODE_DISABLE_SHARE="true"
export HOMEBREW_NO_INSTALL_FROM_API=1
export NEOVIDE_FRAME="transparent"
export NEOVIDE_FORK=1
export GF_BRANCH_SKIP_REMOTE_BRANCHES="yes"
export COMPLETION_WAITING_DOTS="true"
export HOMEBREW_BAT=1
export HOMEBREW_BUNDLE_FILE_PATH="$DOTFILES/Brewfile"
export HOMEBREW_DOWNLOAD_CONCURRENCY="auto"
export HOMEBREW_CASK_OPTS="--fontdir=~/Library/Fonts"
export HOMEBREW_DISPLAY_INSTALL_TIMES=1
export HOMEBREW_NO_ANALYTICS=1
export QMK_HOME='~/code/qmk/qmk_firmware'
export HOME_DIR="$DOTFILES/home"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export NAVI_PATH="$DOTFILES/home/doc"
export NEXTWORD_DATA_PATH="$HOME/.config/nextword-data"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/config"
export STARSHIP_LOG="error"
export VIMFILES="$HOME/code/dotfiles/home/vim"
export XDG_CONFIG_HOME="$HOME/.config"
export GLAB_PAGER="bat"
export PAGER="bat"
export LESS="FrX"

export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig"
export LDFLAGS="-L/opt/homebrew/opt/icu4c/lib -L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/icu4c/include -I/opt/homebrew/opt/openssl@3/include"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$GOBIN"
export PATH="$HOME_DIR/zsh/bin:$PATH"
export PATH="$PATH:$HOME/.spicetify"
export PATH="$PATH:$HOME/.yarn/bin"

_dir_exists $HOME/.cargo/bin && export PATH="$PATH:$HOME/.cargo/bin"

for f in ~/.zsh/private/*.zsh(N); do
    [ -e "$f" ] && source $f || break
done
