export DOTFILES="$HOME/code/dotfiles"
export VIMFILES="$HOME/code/dotfiles/home/vim"
export OCI_DIR=/usr/local/lib
export HOME_DIR="$DOTFILES/home"
export HOMEBREW_CASK_OPTS="--fontdir=~/Library/Fonts"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_BUNDLE_FILE_PATH="$DOTFILES/Brewfile"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
export NAVI_PATH="$DOTFILES/home/doc"
export NEXTWORD_DATA_PATH="$HOME/.config/nextword-data"
export GPG_TTY=$(tty)
export ZSH_AUTOSUGGEST_USE_ASYNC="true"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=239"
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES=":q gco g rubocop"
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL=1
export ZSH_TMUX_AUTOSTART="true"
export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
export HISTSIZE=99999
export SAVEHIST=90000
export COMPLETION_WAITING_DOTS="true"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/config"

export PATH="/usr/local/opt/postgresql@10/bin:/usr/local/opt/node@12/bin:$PATH"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH=$HOME_DIR/zsh/bin:$PATH
export PATH="/usr/local/sbin:$PATH"

for f in ~/.zsh/private/*.zsh(N); do
  [ -e "$f" ] && source $f || break
done
