path=(
/usr/local/opt/rbenv/shims
/usr/local/bin
/usr/bin
/usr/sbin
/bin
/sbin
/usr/X11/bin
/usr/local/heroku/bin
${HOME}/code/custom/go/bin
${HOME}/Library/Python/2.7/bin
${HOME}/.zsh/bin
)

if [[ $(uname) = 'Linux' ]]; then
  IS_LINUX=1

  if (( $+commands[yum] )) ; then
    HAS_YUM=1
  fi

  export USER="$NETID"
  export DISPLAY=:7
  # export rvmsudo_secure_path=1
  export DOTFILES="$HOME/dotfiles"
  export HOME_DIR="$DOTFILES/home"
  export HTML_TIDY="$HOME/.tidyrc"
fi

if [[ $(uname) = 'Darwin' ]]; then
  IS_MAC=1

  if (( $+commands[brew] )) ; then
    HAS_BREW=1
    path=(
    $(brew --prefix)/sbin
    $(brew --prefix)/share/npm/bin
    $(brew --cellar)/coreutils
    $path
    )
  fi

  export GOPATH="$HOME/iCloud/Internal/custom/go"
  export DOTFILES="$HOME/iCloud/Internal/dotfiles"
  export HOME_DIR="$DOTFILES/home"

  export EDITOR='nvim'
  export VISUAL='nvim'
  export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

  export TNS_ADMIN="/usr/local/oracle/network/admin/"
  export SQLPATH="/usr/local/oracle/instantclient_11_2"
  export ORACLE_HOME="/usr/local/oracle/instantclient_11_2"
  export ORACLE_SID="xe"
  export OCI_LIB_DIR="$ORACLE_HOME"
  export OCI_DIR="$ORACLE_HOME"
  export PATH="$PATH:$OCI_LIB_DIR"
  export NLS_LANG="AMERICAN_AMERICA.WE8MSWIN1252"

  [ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh
  export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="jimweirich :q eivm"
fi

if (( $+commands[gls] )) ; then
  HAS_GLS=1
fi

if [ $(command -v cowsay) ]; then
  HAS_COWSAY=1
fi

if [ $(command -v img2xterm) ]; then
  HAS_IMG2XTERM=1
fi

if [ $(command -v grc) ]; then
  HAS_GRC=1
  source `brew --prefix`/etc/grc.bashrc
fi

if [[ -f ~/.fzf.zsh ]]; then
  export FZF_DEFAULT_COMMAND='ag -l -g ""'
  source ~/.fzf.zsh
  export FZF_COMPLETION_TRIGGER=';'
fi

# if [[ -f ~/.dircolors ]]; then
#   eval $( gdircolors -b $HOME/.dircolors )
# fi

# unsetopt promptcr
# setopt notify
