export ZPLUG_HOME=$HOME/.zplug
export ZPLUG_THREADS=1
local zplug_init=$ZPLUG_HOME/init.zsh
if [ ! -f "$zplug_init" ] &> /dev/null; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi
source $zplug_init

source $HOME/.zsh/misc/_utility.zsh

if _linux; then
  export USER="$NETID"
  export rvmsudo_secure_path=1
  export DOTFILES="$HOME/dotfiles"
  alias gls="ls"
fi

if _macos; then
  export DOTFILES="$HOME/code/dotfiles"
  export OCI_DIR=/usr/local/lib
  export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=~/Library/Fonts"
  export HOMEBREW_NO_ANALYTICS=1
  source $DOTFILES/home/zsh/EXA_COLORS
fi

if _exists bat; then
  export BAT_CONFIG_PATH="$HOME/.batconfig"
fi

if _exists nvim; then
  if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
  else
    export VISUAL='nvim'
  fi
else
  export VISUAL='vim'
fi

if _exists fasd; then
  fasd_cache="${ZSH_CACHE_DIR}/fasd-init-cache"
  if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
    fasd --init auto >| "$fasd_cache"
  fi
  source "$fasd_cache"
  unset fasd_cache

  alias v="f -e \"$VISUAL\""
  alias o='a -e open'
fi

if zplug check 'denysdovhan/spaceship-prompt'; then
  SPACESHIP_PROMPT_ORDER=(
    time          # Time stampts section
    user          # Username section
    dir           # Current directory section
    host          # Hostname section
    hg            # Mercurial section (hg_branch  + hg_status)
    # package     # Package version
    # node        # Node.js section
    ruby          # Ruby section
    elixir        # Elixir section
    xcode         # Xcode section
    swift         # Swift section
    golang        # Go section
    php           # PHP section
    rust          # Rust section
    haskell       # Haskell Stack section
    julia         # Julia section
    # docker      # Docker section
    aws           # Amazon Web Services section
    venv          # virtualenv section
    conda         # conda virtualenv section
    pyenv         # Pyenv section
    dotnet        # .NET section
    ember         # Ember.js section
    kubecontext   # Kubectl context section
    exec_time     # Execution time
    line_sep      # Line break
    battery       # Battery level and status
    vi_mode       # Vi-mode indicator
    jobs          # Background jobs indicator
    exit_code     # Exit code section
    char          # Prompt character char
  )

  SPACESHIP_RPROMPT_ORDER=(
    git           # Git section (git_branch + git_status)
  )

  export SPACESHIP_VI_MODE_SHOW="false"
  export SPACESHIP_CHAR_SYMBOL="➜  "
  export SPACESHIP_RUBY_COLOR="blue"
  export SPACESHIP_RUBY_SYMBOL="🔻 "
  export SPACESHIP_PROMPT_SEPARATE_LINE="true"
fi

export EDITOR="$VISUAL"
export HOME_DIR="$DOTFILES/home"
export LESS='-F -g -i -M -R -S -w -X -z-4'
export PATH=$PATH:~/bin
export PATH=/usr/local/opt/python/libexec/bin:$PATH

if _exists go; then
  export PATH=$PATH:$HOME/code/go/bin
fi
