source $HOME/.antigen/antigen.zsh
source ~/.fresh/build/shell.sh

antigen use oh-my-zsh

if [[ $IS_MAC -eq 1 ]]; then
   antigen bundle brew
   antigen bundle brew-cask
   antigen bundle osx
   antigen bundle vagrant
   antigen bundle heroku
fi

antigen bundle $HOME/.zsh/plugins/gary

antigen bundle bundler
antigen bundle capistrano
antigen bundle catimg
antigen bundle colored-man
antigen bundle colorize
antigen bundle command-not-found
antigen bundle cp
antigen bundle extract
antigen bundle fasd
antigen bundle gem
antigen bundle git
antigen bundle github
antigen bundle git-flow
antigen bundle git-remote-branch
antigen bundle gitignore
antigen bundle pip
antigen bundle rails
antigen bundle rake
antigen bundle rake-fast
antigen bundle rbenv
antigen bundle ruby
# antigen bundle safe-paste

antigen bundle bobthecow/git-flow-completion
# antigen bundle djui/alias-tips
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme $HOME/.zsh/themes gary_pure_mod
# antigen bundle sindresorhus/pure

antigen apply

for f ($HOME/.zsh/*.zsh) {source $f}
for f ($HOME/.zsh/private/*.zsh) {source $f}

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES+=(
  default                       'none'
  unknown-token                 'fg=red,bold'
  reserved-word                 'fg=yellow'
  alias                         'fg=none,bold'
  builtin                       'fg=none,bold'
  function                      'fg=none,bold'
  command                       'fg=none,bold'
  hashed-command                'fg=none,bold'
  path                          'fg=cyan'
  globbing                      'fg=cyan'
  history-expansion             'fg=blue'
  single-hyphen-option          'fg=magenta'
  double-hyphen-option          'fg=magenta'
  back-quoted-argument          'fg=magenta,bold'
  single-quoted-argument        'fg=green'
  double-quoted-argument        'fg=green'
  dollar-double-quoted-argument 'fg=cyan'
  back-double-quoted-argument   'fg=cyan'
  assign                        'none'
)

if [[ $HAS_IMG2XTERM -eq 1 ]]; then
  if (( RANDOM % 2 ));
  then img2xterm $HOME/.zsh/plugins/meeseeks_iterm.png;
  else img2xterm $HOME/.zsh/plugins/kody.png;
fi

  green "-------------------------------"
  echo "$(uptime | awk -F'[a-z]:' '{ print "Load:"$2 }') | $(battery)"
elif [[ $HAS_COWSAY -eq 1 ]]; then
  echo "CAN DO!" | cowsay -f $HOME/.zsh/plugins/cows/meeseeks.cow
else
  uptime
fi

[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
