typeset -F4 SECONDS=0
# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
  # if _exists glab; then
  #   glab completion -s zsh > "$(brew --prefix)/share/zsh/site-functions/_glab"
  # fi
  # ^^ i dont think we have to keep remaking this
fi

# if _exists fasd
# then
#   fasd_cache="${HOME}/.cache/fasd-init-cache"
#   if [[ "$commands[fasd]" -nt "$fasd_cache" || ! -s "$fasd_cache" ]]; then
#     fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install \
#       zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
#   fi
#   source "$fasd_cache"
#   unset fasd_cache
# fi

# ------------------
# Initialize modules
# ------------------

ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if (( ${+commands[curl]} )); then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  else
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
fi

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

# Initialize modules.
source ${ZIM_HOME}/init.zsh

zstyle ':zim:input' double-dot-expand yes

# ------------------------------
# Post-init module configuration
# ------------------------------
#
# zsh-history-substring-search

zmodload -F zsh/terminfo +p:terminfo
# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
for key ('^[[A' '^P' ${terminfo[kcuu1]}) bindkey ${key} history-substring-search-up
for key ('^[[B' '^N' ${terminfo[kcud1]}) bindkey ${key} history-substring-search-down
for key ('k') bindkey -M vicmd ${key} history-substring-search-up
for key ('j') bindkey -M vicmd ${key} history-substring-search-down
unset key
# }}} End configuration added by Zim install

if [[ $(zsh --version | awk '{print $2}') > 5.0.7 ]]; then
  eval "$(starship init zsh)"
fi

for f ($DOTFILES/home/zsh/*.sh) { source $f }

# if _file_exists /usr/local/bin/rubocop-daemon-wrapper/rubocop; then
#   export PATH="/usr/local/bin/rubocop-daemon-wrapper:$PATH"
# fi

export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=100000000
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export HISTTIMEFORMAT="[%F %T] "

setopt APPEND_HISTORY       # Immediately append to the history file, not just when a term is killed
setopt EXTENDED_HISTORY     # Write the history file in the ":start:elapsed;command" format.
setopt HIST_IGNORE_ALL_DUPS # Do not display a line previously found.
setopt HIST_REDUCE_BLANKS   # Remove superfluous blanks before recording entry.
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY        # Share history between all sessions.

setopt ALWAYS_TO_END        # always move to the end of the word if completion worked
setopt AUTO_MENU            # show completion menu on successive tab press
setopt COMPLETE_IN_WORD     # trigger autocompletion within word

unsetopt CORRECT_ALL        # don't autocorrect when thefuck does it better.
unsetopt FLOWCONTROL        # gives me back ^-S

autoload -U select-word-style
select-word-style bash

echo ""

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.asdf/asdf.sh ] && source ~/.asdf/asdf.sh

source "$HOME/code/fzf-widgets/init.zsh"
export PATH=$HOME_DIR/zsh/bin:$PATH
export PATH=$PATH:$HOME/.spicetify

# # https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1413
# export PATH="/opt/homebrew/opt/icu4c/bin:$PATH"
# export PATH="/opt/homebrew/opt/icu4c/sbin:$PATH"
# export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
# export PATH="/opt/homebrew/bin:$PATH"
# export PATH="/opt/homebrew/sbin:$PATH"

# export PATH="$HOME/.asdf/shims:$PATH"
# source $HOME/.config/broot/launcher/bash/br

export GEM_PATH="$(gem environment gempath)"

e_success "${SHELL} ${ZSH_VERSION} loaded in ${(M)$(( SECONDS * 1000 ))#*.?} ms"
