DISABLE_AUTO_UPDATE="true"
source $DOTFILES/submodules/zgen/zgen.zsh

if ! zgen saved; then
  zgen oh-my-zsh

  if [[ $IS_MAC -eq 1 ]]; then
    zgen oh-my-zsh plugins/brew
    zgen oh-my-zsh plugins/heroku
  fi

  zgen oh-my-zsh plugins/bundler
  zgen oh-my-zsh plugins/fasd
  zgen oh-my-zsh plugins/github
  zgen oh-my-zsh plugins/rake-fast
  zgen oh-my-zsh plugins/rbenv
  zgen oh-my-zsh plugins/zsh_reload
  zgen oh-my-zsh plugins/command-not-found
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/docker-compose

  zgen load Tarrasch/zsh-colors
  zgen load djui/alias-tips
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load mafredri/zsh-async
  zgen load zsh-users/zsh-completions src

  zgen load $DOTFILES/submodules/pure

  zgen save
fi

for f ($HOME/.zsh/*.zsh) {source $f}

for f in ~/.zsh/private/*.zsh(N); do
  [ -e "$f" ] && source $f || break
done

if [[ $HAS_IMGCAT -eq 1 ]]; then
  if [[ -a $HOME/iCloud/Public/tiny_rick.jpg ]]; then
    imgcat $HOME/iCloud/Public/tiny_rick.jpg
  fi
elif [[ $HAS_IMG2XTERM -eq 1 ]]; then
  img2xterm $HOME/.zsh/plugins/meeseeks_iterm.png;
elif [[ $HAS_COWSAY -eq 1 ]]; then
  echo "CAN DO!" | cowsay -f $HOME/.zsh/plugins/cows/meeseeks.cow
fi
echo "$(uptime | awk -F'[a-z]:' '{ print "Load:"$2 }') | $(battery)"

ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zshrc.local)
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES=":q eivm evimrc ezshrc _ gls"
