# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'gem-shut-the-fuck-up'
gem 'awesome_print'
gem 'annotate'
gem 'gem-browse'
gem 'docker-sync'
gem 'gem-ctags'
gem 'ghi'
gem 'hirb'
gem 'neovim'
gem 'otask'
gem 'pry'
gem 'pry-bloodline'
gem 'pry-coolline'
gem 'pry-doc'
gem 'pry-theme'
gem 'pry-toys'
gem 'rb-appscript'
gem 'rb-readline'
gem 'rubocop'
gem 'sketches'
gem 'wallpaper'
