#!/bin/bash

function run_test {
  echo $(date +"%Y-%m-%d %H:%M") [$(basename $PWD)]:  $(<./.git/COMMIT_EDITMSG) >> ~/Dropbox/Internal/git_commits.log
  return 1
}

case "${1}" in
    --about )
        echo "Log commit messages to a local file"
        ;;
    * )
        run_test
        ;;
esac

# log_file = "#{ENV['HOME']}/Dropbox/Internal/git_commits.log"
# repo = Git.open(Dir.pwd)
# repo_name = Dir.pwd[%r{[\.\-\w]+$}]                       # top directory
# date = repo.log.first.date.strftime("%Y-%m-%d-%H-%M-%S")  # format date
# message = repo.log.first.message.lines.first.strip        # just first line
# branch = repo.log.first.name
# File.open(log_file, "a") do |log|
#   log.puts "#{date} [#{repo_name}:#{branch}] #{message}"
# end
