update

upgrade

tap homebrew/dupes
tap jimbojsb/launchrocket

tap phinze/homebrew-cask
install brew-cask

cask install xquartz

install ansible
install apple-gcc42
install archey
install autoconf
install cmake
install coreutils
install cowsay
install ctags
install curl
install curl-ca-bundle
install direnv
install fasd
install ffind
install fontconfig
install fontforge
install gcc
install git
install git-cal
install git-flow
install gnutls
install grc
install grep
install hr
install htop-osx
install hub
install ifstat
install imagemagick
install legit
install lua
install mackup
install macvim --override-system-vim --with-lua
install openssl
install postgresql
install python
install python3
install rainbarf
install rbenv
install rbenv-binstubs
install rbenv-gem-rehash
install rbenv-use
install rbenv-whatis
install readline
install reattach-to-user-namespace
install redis
install ruby-build
install sloccount
install source-highlight
install sqlite
install ssh-copy-id
install the_silver_searcher
install tig
install tmux
install tmux-mem-cpu-load
install tomcat
install tree
install webkit2png
install zsh
install zsh-syntax-highlighting

cask install adium
cask install appcleaner
cask install bartender
cask install bettertouchtool
cask install caffeine
cask install chameleon-ssd-optimizer
cask install coconutbattery
cask install colorpicker
cask install colorpicker-developer
cask install controlplane
cask install daisydisk
cask install default-folder-x
cask install dropbox
cask install evernote
cask install fake
cask install fantastical
cask install firefox
cask install flash
cask install fluid
cask install flux
cask install github
cask install google-chrome
cask install hipchat
cask install imageoptim
cask install instacast
cask install kaleidoscope
cask install karabiner
cask install keyboard-cleaner
cask install knox
cask install launchrocket
cask install lingon-x
cask install macvim
cask install marked
cask install minecraft
cask install moom
cask install name-mangler
cask install onepassword
cask install onyx
cask install pacifist
cask install rcdefaultapp
cask install secrets
cask install seil
cask install shortcat
cask install skype
cask install soulver
cask install sourcetree
cask install spotify
cask install steam
cask install superduper
cask install textexpander
cask install timemachineeditor
cask install transmit
cask install vagrant
cask install virtualbox
cask install vlc
cask install xtrafinder
cask install qlcolorcode
cask install qlmarkdown
cask install qlprettypatch
cask install qlstephen
cask install quicklook-csv
cask install quicklook-json
cask install webp-quicklook
cask install suspicious-package
# cask install betterzipql

tap homebrew/versions

cleanup
