update

upgrade

tap homebrew/dupes
tap jimbojsb/launchrocket

tap phinze/homebrew-cask
install brew-cask

cask install xquartz

install ack
install apple-gcc42
install asciidoc
install aspell
install autoconf
install automake
install bash
install boost
install brew-desc
install cmake
install coconutbattery
install coreutils
install cowsay
install cscope
install ctags
install curl
install curl-ca-bundle
install ddclient
install direnv
install docbook
install docbook-xsl
install emacs
install enscript
install fasd
install ffind
install figlet
install firefox-aurora
install fish
install fontconfig
install fontforge
install freetype
install gcc
install gdbm
install gettext
install git
install git-cal
install git-flow
install gitsh
install glib
install gmp
install gnu-getopt
install gnupg
install gnutls
install go
install gpgme
install grc
install grep
install heroku-toolbelt
install htop-osx
install hub
install ifstat
install imagemagick
install jpeg
install legit
install lftp
install libassuan
install libevent
install libffi
install libgcrypt
install libgpg-error
install libidn
install libksba
install libmpc
install libotr
install libpng
install libtasn1
install libtiff
install libtool
install libxml2
install libxslt
install libyaml
install loudmouth
install lynx
install mackup
install macvim
install mcabber
install mcrypt
install mercurial
install mobile-shell
install mpfr
install multimarkdown
install mutt
install narwhal
install nettle
install node
install openssl
install ossp-uuid
install p11-kit
install pcre
install perl
install phantomjs
install php54
install pkg-config
install postgresql
install protobuf
install pstree
install pth
install python
install python3
install qt
install rbenv
install rbenv-binstubs
install rbenv-use
install rbenv-whatis
install rbenv-gem-rehash
install readline
install reattach-to-user-namespace
install rename
install rhino
install ringojs
install shortcat
install source-highlight
install sqlite
install ssh-copy-id
install the_silver_searcher
install tig
install tintin
install tmux
install tmux-mem-cpu-load
install todo-txt
install tokyo-cabinet
install tomcat
install tree
install vim --override-system-vi
install webkit2png
install weechat
install wget --enable-iri
install xmlto
install xz
install zlib
install zsh
install zsh-syntax-highlighting

cask install adium
cask install appcleaner
cask install bartender
cask install bettertouchtool
cask install betterzip
cask install betterzipql
cask install bowtie
cask install caffeine
cask install coconutbattery
cask install contexts
cask install controlplane
cask install cornerstone
cask install crashplan
cask install day-o
cask install daisydisk
cask install default-folder-x
cask install delibar
cask install dropbox
cask install evernote
cask install fake
cask install fantastical
cask install firefox
cask install flash
cask install fluid
cask install flux
cask install github
cask install google-chrome
cask install growlvoice
cask install hall
cask install handbrake
cask install iexplorer
cask install imageoptim
cask install instacast
cask install kaleidoscope
cask install keyboard-cleaner
cask install keyremap4macbook
cask install knox
cask install launchrocket
cask install macvim
cask install marked
cask install menubarfilter
cask install minecraft
cask install moom
cask install name-mangler
cask install navicat-for-oracle
cask install omnifocus
cask install onyx
cask install pacifist
cask install pckeyboardhack
cask install qlcolorcode
cask install qlmarkdown
cask install qlprettypatch
cask install qlstephen
cask install quicklook-csv
cask install quicklook-json
cask install rcdefaultapp
cask install secrets
cask install skitch
cask install skype
cask install soulver
cask install sourcetree
cask install sparrow
cask install spotify
cask install steam
cask install sublime-text
cask install superduper
cask install suspicious-package
cask install textexpander
cask install the-unarchiver
cask install timemachineeditor
cask install transmit
cask install vagrant
cask install virtualbox
cask install vlc
cask install webp-quicklook
cask install xslimmer
cask install xtrafinder

tap homebrew/versions

cleanup
