vim.g.mapleader = ","
vim.g.maplocalleader = "\\"

require('vimp')

vimp.map_command('PrettyJSON', function()
  vim.cmd("execute '%!python -m json.tool'")
end)

vimp.nmap({'silent'}, '!',       ':ALEFix<CR>')
vimp.nmap({'silent'}, '-',       ':Switch<CR>')
vimp.nmap({'silent'}, ';',       ':Buffers<CR>')
vimp.nmap({'silent'}, '<C-P>',   ':Files<CR>')
vimp.nmap({'silent'}, '<Del>',   ':A<cr>')
vimp.nmap({'silent'}, '<c-g>',   ':InfoWindowCustomToggle<cr>')
vimp.nmap({'silent'}, '<s-tab>', '<c-w>w')
vimp.nmap({'silent'}, 'K',       ':call <SID>show_documentation()<CR>')
vimp.nmap({'silent'}, 'Q',       ':Sayonara<cr>')
vimp.nmap({'silent'}, 'S',       ':call BreakHere()<CR>')
vimp.nmap({'silent'}, '[!',      '<Plug>(ale_previous_wrap)')
vimp.nmap({'silent'}, '[<Tab>',  ':SidewaysLeft<cr>')
vimp.nmap({'silent'}, '[c',      '<Plug>(GitGutterPrevHunk)')
vimp.nmap({'silent'}, '[n',      ':call mappings#cycle_numbering()<CR>')
vimp.nmap({'silent'}, '[s',      '<Plug>VimyouautocorrectPrevious')
vimp.nmap({'silent'}, ']!',      '<Plug>(ale_next_wrap)')
vimp.nmap({'silent'}, ']<Tab>',  ':SidewaysRight<cr>')
vimp.nmap({'silent'}, ']c',      '<Plug>(GitGutterNextHunk)')
vimp.nmap({'silent'}, ']n',      ':call mappings#cycle_numbering()<CR>')
vimp.nmap({'silent'}, ']s',      '<Plug>VimyouautocorrectNext')
vimp.nmap({'silent'}, 'ga',      '<Plug>(EasyAlign)')
vimp.nmap({'silent'}, 'sJ',      ':SplitjoinSplit<cr>')
vimp.nmap({'silent'}, 'sK',      ':SplitjoinJoin<cr>')
vimp.nmap({'silent'}, 'sj',      ':SplitjoinSplit<cr>')
vimp.nmap({'silent'}, 'sk',      ':SplitjoinJoin<cr>')

vimp.nnoremap('zM',       'zM:echo &foldlevel<cr>')
vimp.nnoremap('zR',       'zR:echo &foldlevel<cr>')
vimp.nnoremap('zm',       'zm:echo &foldlevel<cr>')
vimp.nnoremap('zr',       'zr:echo &foldlevel<cr>')
vimp.nnoremap({'silent'}, '<Down>',  ':call animate#window_delta_height(15)<CR>')
vimp.nnoremap({'silent'}, '<Up>',    ':call animate#window_delta_height(-15)<CR>')
vimp.nnoremap({'silent'}, '<Right>', ':call animate#window_delta_width(30)<CR>')
vimp.nnoremap({'silent'}, '<Left>',  ':call animate#window_delta_width(-30)<CR>')
