-- local M = {
--   "folke/tokyonight.nvim",
--   lazy = false,
--   priority = 1000,
--   opts = {},
-- }
-- function M.config()
--   require("tokyonight").setup({
--     styles = {
--       comments  = { italic = true },
--       keywords  = { bold = true },
--       functions = { bold = true },
--       variables = { bold = true },
--       sidebars  = "dark",
--       floats    = "dark",
--     },
--   })
--   vim.cmd([[colorscheme tokyonight-night]])
-- end

local M = {
  "bluz71/vim-nightfly-colors",
  name = "nightfly",
  lazy = false,
  priority = 1000
}

function M.config()
  vim.cmd.colorscheme 'nightfly'
  -- require("rose-pine").setup({
  --   dark_variant = "moon", -- main, moon, or dawn
  --   dim_inactive_windows = true,
  --   extend_background_behind_borders = true,
  --
  --   enable = {
  --     terminal = true,
  --     legacy_highlights = false, -- Improve compatibility for previous versions of Neovim
  --     migrations = true,      -- Handle deprecated options automatically
  --   },
  --
  --   styles = {
  --     bold = true,
  --     italic = true,
  --     transparency = true,
  --   },
  --
  --   groups = {
  --     border = "muted",
  --     link = "iris",
  --     panel = "surface",
  --
  --     error = "love",
  --     hint = "iris",
  --     info = "foam",
  --     note = "pine",
  --     todo = "rose",
  --     warn = "gold",
  --
  --     git_add = "foam",
  --     git_change = "rose",
  --     git_delete = "love",
  --     git_dirty = "rose",
  --     git_ignore = "muted",
  --     git_merge = "iris",
  --     git_rename = "pine",
  --     git_stage = "iris",
  --     git_text = "rose",
  --     git_untracked = "subtle",
  --
  --     h1 = "iris",
  --     h2 = "foam",
  --     h3 = "rose",
  --     h4 = "gold",
  --     h5 = "pine",
  --     h6 = "foam",
  --   },
  --
  --   palette = {
  --     -- Override the builtin palette per variant
  --     -- moon = {
  --     --     base = '#18191a',
  --     --     overlay = '#363738',
  --     -- },
  --   },
  --
  --   -- NOTE: Highlight groups are extended (merged) by default. Disable this
  --   -- per group via `inherit = false`
  --   highlight_groups = {
  --     -- Comment = { fg = "foam" },
  --     -- StatusLine = { fg = "love", bg = "love", blend = 15 },
  --     -- VertSplit = { fg = "muted", bg = "muted" },
  --     -- Visual = { fg = "base", bg = "text", inherit = false },
  --   },
  --
  --   before_highlight = function(group, highlight, palette)
  --     -- Disable all undercurls
  --     -- if highlight.undercurl then
  --     --     highlight.undercurl = false
  --     -- end
  --     --
  --     -- Change palette colour
  --     -- if highlight.fg == palette.pine then
  --     --     highlight.fg = palette.foam
  --     -- end
  --   end,
  -- })
end

-- return M

-- local M = {
--   "vague2k/vague.nvim",
--   lazy = false,    -- make sure we load this during startup if it is your main colorscheme
--   priority = 1000, -- make sure to load this before all the other plugins
-- }
--
-- function M.config()
--   require("vague").setup({
--     -- optional configuration here
--     transparent = false, -- don't set background
--     -- disable bold/italic globally in `style`
--     bold = true,
--     italic = true,
--     style = {
--       -- "none" is the same thing as default. But "italic" and "bold" are also valid options
--       boolean = "bold",
--       number = "none",
--       float = "none",
--       error = "bold",
--       comments = "italic",
--       conditionals = "none",
--       functions = "none",
--       headings = "bold",
--       operators = "none",
--       strings = "italic",
--       variables = "none",
--
--       -- keywords
--       keywords = "none",
--       keyword_return = "italic",
--       keywords_loop = "none",
--       keywords_label = "none",
--       keywords_exception = "none",
--
--       -- builtin
--       builtin_constants = "bold",
--       builtin_functions = "italic",
--       builtin_types = "bold",
--       builtin_variables = "italic",
--     },
--   })
--   vim.cmd("colorscheme vague")
-- end

-- local M = {
--   "shaunsingh/nord.nvim",
--   lazy = false,
--   priority = 1000,
--   opts = {},
-- }
-- function M.config()
--   vim.g.nord_contrast = true
--   vim.g.nord_borders = false
--   vim.g.nord_disable_background = false
--   vim.g.nord_italic = false
--   vim.g.nord_uniform_diff_background = true
--   vim.g.nord_bold = false
--
--   -- Load the colorscheme
--   require('nord').set()
-- end

-- lazy.nvim
-- local M = { "comfysage/cuddlefish.nvim" }
--
-- function M.config()
--   require('cuddlefish').setup({
--     theme = {
--       accent = 'pink',
--     },
--     editor = {
--       transparent_background = true,
--     },
--     style = {
--       tabline = { 'reverse' },
--       search = { 'italic', 'reverse' },
--       incsearch = { 'italic', 'reverse' },
--       types = { 'bold' },
--       keyword = { 'italic' },
--       comment = { 'italic' },
--     },
--     -- overrides = function(colors)
--     --   return {}
--     -- end,
--   })
--
--   vim.cmd.colorscheme [[cuddlefish]]
-- end
--
-- return M

-- local M = {
--   "nyoom-engineering/oxocarbon.nvim"
--   -- Add in any other configuration;
--   --   event = foo,
--   --   config = bar
--   --   end,
-- }
--
-- function M.config()
--   vim.opt.background = "dark" -- set this to dark or light
--   vim.cmd.colorscheme "oxocarbon"
--   vim.cmd('hi MiniTablineCurrent gui=bold')
--   vim.cmd('hi MiniIconsGrey guibg=NONE')
-- end
--
-- return M

--
-- local M = {
--   "tiagovla/tokyodark.nvim"
-- }
--
-- function M.config()
--   require("tokyodark").setup({
--     -- styles = {
--     --   functions = { bold = true }, -- style for functions
--     --   variables = { bold = true }, -- style for variables
--     -- },
--   })
--
--   vim.cmd [[colorscheme tokyodark]]
-- end
--
-- return M

-- local M = {
--   "rose-pine/neovim",
--   name = "rose-pine",
-- }
-- function M.config()
--   require("rose-pine").setup({
--     variant = "moon",
--     dark_variant = "moon",
--     dim_inactive_windows = true,
--     extend_background_behind_borders = true,
--
--     enable = {
--       terminal = true,
--       legacy_highlights = false,
--       migrations = true,
--     },
--
--     styles = {
--       bold = true,
--       italic = true,
--       transparency = true,
--     },
--   })
--
--   vim.cmd("colorscheme rose-pine-moon")
-- end
--
-- return M

-- local M = { "aliqyan-21/darkvoid.nvim" }
--
-- function M.config()
-- 	-- require("rose-pine").setup({
-- 	-- 	variant = "moon",
-- 	-- 	dark_variant = "moon",
-- 	-- 	dim_inactive_windows = true,
-- 	-- 	extend_background_behind_borders = true,
-- 	--
-- 	-- 	enable = {
-- 	-- 		terminal = true,
-- 	-- 		legacy_highlights = false,
-- 	-- 		migrations = true,
-- 	-- 	},
-- 	--
-- 	-- 	styles = {
-- 	-- 		bold = true,
-- 	-- 		italic = true,
-- 	-- 		transparency = true,
-- 	-- 	},
-- 	-- })
--
-- 	vim.cmd("colorscheme darkvoid")
-- end
--
return M
