local M = {
  "folke/which-key.nvim",
  event = "VeryLazy",
  enabled = true,
}

function M.config()
  local whichkey = require("which-key")

  whichkey.setup({
    preset = "helix",
    sort = { "alphanum", "order" },
    -- win = {
    --   no_overlap = true,
    --   border = "double",
    -- },
    triggers = {
      { "<auto>",  mode = "nxsot" },
      { "yo",      mode = { "n" } },
      { "<space>", mode = { "n" } },
    },
  })

  whichkey.add({
    {
      mode = { "o", "v" }, -- NORMAL and VISUAL mode
      { "a(", hidden = true },
      { "a)", hidden = true },
      { "i(", hidden = true },
      { "i)", hidden = true },
      { 'a"', hidden = true },
      { 'i"', hidden = true },
      { "a'", hidden = true },
      { "i'", hidden = true },
      { "a>", hidden = true },
      { "i>", hidden = true },
      { "a[", hidden = true },
      { "i[", hidden = true },
      { "a]", hidden = true },
      { "i]", hidden = true },
      { "a`", hidden = true },
      { "i`", hidden = true },
      { "a{", hidden = true },
      { "i{", hidden = true },
      { "a}", hidden = true },
      { "i}", hidden = true },
      { "a<", hidden = true },
      { "i<", hidden = true },
      { "aB", hidden = true },
      { "iB", hidden = true },
      { "ab", hidden = true },
      { "ib", hidden = true },
      { "P",  hidden = true },
      { "p",  hidden = true },
      { "H",  hidden = true },
      { "L",  hidden = true },
      { "j",  hidden = true },
      { "k",  hidden = true },
      { "/",  hidden = true },
      { "<",  hidden = true },
      { ">",  hidden = true },
    },

    { "<leader>",   group = "leader" },
    { "<space>",    group = "spacebar" },

    { "<space>e",   desc = "Edit..." },
    { "<space>ee",  desc = "In EE..." },
    { "<space>et",  desc = "Specs..." },
    { "<space>ete", desc = "In EE..." },

    -- { "!",          hidden = true },
    { "[",          group = "leftbrakcet" },
    { "[!",         desc = "Prev Diagnostic Issue" },
    { "[%",         desc = "Prev Unmatched Group" },
    { "[<C-L>",     hidden = true },
    { "[<C-Q>",     hidden = true },
    { "[<C-T>",     hidden = true },
    { "[<space>",   hidden = true },
    { "[A",         hidden = true },
    { "[B",         hidden = true },
    { "[C",         hidden = true },
    { "[L",         hidden = true },
    { "[Q",         hidden = true },
    { "[a",         hidden = true },
    { "[e",         hidden = true },
    { "[f",         desc = "Prev File in Directory" },
    { "[l",         hidden = true },
    { "[n",         desc = "TODO comments" },
    { "[o",         group = "Turn on..." },
    { "[o+",        desc = "Cursor Line and Column" },
    { "[o-",        desc = "Cursor Line" },
    { "[o_",        desc = "Cursor Line" },
    { "[ob",        desc = "Light Background" },
    { "[oc",        desc = "Cursor Line" },
    { "[od",        desc = "Diff This" },
    { "[oh",        desc = "Search" },
    { "[oi",        desc = "Ignore Case" },
    { "[ol",        desc = "List Characters" },
    { "[on",        desc = "Numbers" },
    { "[op",        desc = "Paste Mode" },
    { "[or",        desc = "Relative Numbers" },
    { "[os",        desc = "Spelling" },
    { "[ou",        desc = "Cursor Column" },
    { "[ov",        desc = "Virtual Edit" },
    { "[ow",        desc = "Wrap" },
    { "[ox",        desc = "Cursor Line and Column" },
    { "[o|",        desc = "Cursor Column" },
    { "[q",         hidden = true },
    { "[r",         hidden = true },
    { "[s",         desc = "Prev Misspelled Word" },
    { "[t",         desc = "Prev Tab" },
    { "[x",         hidden = true },

    { "\\",         group = "localleader" },
    { "\\p",        desc = "Pry..." },
    { "\\s",        desc = "Sideways..." },

    { ",",          group = "leader" },
    { ",b",         group = "buffer" },
    { ",c",         group = "code" },
    { ",d",         group = "?peek" },
    { ",g",         group = "git" },
    { ",h",         group = "uhh idk" },

    { "]",          group = "rightbracket" },
    { "]!",         desc = "Next Diagnostic Issue" },
    { "]%",         desc = "Next Unmatched Group" },
    { "]<C-L>",     hidden = true },
    { "]<C-Q>",     hidden = true },
    { "]<C-T>",     hidden = true },
    { "]<space>",   hidden = true },
    { "]A",         hidden = true },
    { "]B",         hidden = true },
    { "]C",         hidden = true },
    { "]L",         hidden = true },
    { "]Q",         hidden = true },
    { "]a",         hidden = true },
    { "]e",         hidden = true },
    { "]f",         desc = "Next File in Directory" },
    { "]l",         hidden = true },
    { "]n",         desc = "TODO comments" },
    { "]o",         group = "Turn off..." },
    { "]o+",        desc = "Cursor Line and Column" },
    { "]o-",        desc = "Cursor Line" },
    { "]o_",        desc = "Cursor Line" },
    { "]ob",        desc = "Light Background" },
    { "]oc",        desc = "Cursor Line" },
    { "]od",        desc = "Diff This" },
    { "]oh",        desc = "Search" },
    { "]oi",        desc = "Ignore Case" },
    { "]ol",        desc = "List Characters" },
    { "]on",        desc = "Numbers" },
    { "]op",        desc = "Paste Mode" },
    { "]or",        desc = "Relative Numbers" },
    { "]os",        desc = "Spelling" },
    { "]ou",        desc = "Cursor Column" },
    { "]ov",        desc = "Virtual Edit" },
    { "]ow",        desc = "Wrap" },
    { "]ox",        desc = "Cursor Line and Column" },
    { "]o|",        desc = "Cursor Column" },
    { "]q",         hidden = true },
    { "]r",         hidden = true },
    { "]s",         desc = "Next Misspelled Word" },
    { "]t",         desc = "Next Tab" },
    { "]x",         hidden = true },

    { "g",          group = "goto" },
    { "g#",         hidden = true },
    { "g*",         hidden = true },
    { "gc",         group = "comment" },
    { "gcc",        desc = "Comment Line" },
    { "gl",         desc = "Git..." },
    { "go",         desc = "Open Files..." },
    { "gO",         desc = "LSP: Document Symbols" },
    { "gr",         group = "LSP" },
    { "gra",        desc = "LSP: Code Actions" },
    { "gri",        desc = "LSP: Go to Implementation" },
    { "grn",        desc = "LSP: Rename" },
    { "grr",        desc = "LSP: Go to References" },
    { "y",          group = "yank" },
    -- { "yp",         group = "yank path" },

    -- { "yo",         "<Plug>(unimpaired-toggle)",         group = "toggles" },
    -- { "yo+",        hidden = true },
    -- { "yo-",        hidden = true },
    -- { "yo_",        hidden = true },
    -- { "yob",        desc = "background (dark/light)" },
    -- { "yoc",        desc = "cursor line" },
    -- { "yod",        desc = "diffs" },
    -- { "yoh",        desc = "highlight search" },
    -- { "yoi",        desc = "ignorecase" },
    -- { "yol",        desc = "list chars" },
    -- { "yon",        desc = "absolute numbers" },
    -- { "yop",        hidden = true },
    -- { "yor",        desc = "relative numbers" },
    -- { "yos",        desc = "spelling" },
    -- { "you",        desc = "cursor column" },
    -- { "yov",        desc = "virtualedit" },
    -- { "yow",        desc = "word wrapping" },
    -- { "yox",        desc = "cursor line + cursor column" },
    -- { "yo|",        hidden = true },
    { "z",          group = "spelling/folds" },
  })

  s_nmap("<leader>?", function()
    require("which-key").show({ global = false })
  end, "Buffer Local Keymaps (which-key)")
end

return M
