ZSH=$HOME/.oh-my-zsh
ZSH_THEME="gary"
COMPLETION_WAITING_DOTS="true"

plugins=(command-coloring git zsh-syntax-highlighting brew osx heroku gem cap ruby rvm git-flow eifion vagrant nyan battery themes git-hubflow safe-paste zeus zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

for f ($HOME/.zsh/*.zsh) {source $f}
for f ($HOME/.zsh/private/*.zsh) {source $f}

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

uptime | cowsay -f small
echo ""
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
