for f ($HOME/.zsh/*.zsh) {source $f}
for f ($HOME/.zsh/private/*.zsh) {source $f}

local _ANTIGEN_INSTALL_DIR="$HOME/.zsh/antigen"

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

if (( $+commands[cowsay] )); then
  echo "OOOOOOOOOOOOH: $(uptime)" | cowsay -f $HOME/.zsh/plugins/cows/meeseeks.cow
else
  uptime
fi
echo ""

if (( $+commands[direnv] )) ; then
  eval "$(direnv hook zsh)"
fi

# zsh-bd
. $HOME/.zsh/plugins/bd/bd.zsh

function update_terminal_title() {
  print -Pn "\e]0;%n :: %~/ \a"
}

if [[ -f ~/.fzf.zsh ]]; then
  export FZF_DEFAULT_COMMAND='ag -l -g ""'
  source ~/.fzf.zsh
fi

if [[ $IS_LINUX -eq 1 ]]; then
  source /etc/profile.d/rvm.sh
fi

if [[ $IS_MAC -eq 1 ]]; then
  antigen bundle brew
  antigen bundle brew-cask
fi

antigen-use oh-my-zsh

antigen bundles <<EOB
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-completions
  battery
  capistrano
  colored-man
  colorize
  gem
  # git
  gitignore
  git-extras
  git-flow
  heroku
  mosh
  osx
  pip
  rails
  rake
  rake-fast
  ruby
  themes
  tmuxinator
  vagrant
  $HOME/.zsh/plugins/eifion
  zeus
  sindresorhus/pure
EOB

# antigen theme $HOME/.zsh/gary_pure_mod.zsh-theme
antigen apply


[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

function box_name {
if [[ -f ~/.box-name  ]]; then
  if [[ $(cat ~/.box-name) = 'STAGING'  ]]; then
    echo "%{$fg[yellow]STAGING"
  elif [[ $(cat ~/.box-name) = 'PRODUCTION'  ]]; then
    echo "%{$fg[red]PRODUCTION"
  else
    cat ~/.box-name
  fi
else
  hostname -s
fi
}

RPROMPT="$(box_name)"
